---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: golangci/golangci-lint:latest
    environment:
      CGO_ENABLED: 0
    commands:
      - golangci-lint run
    depends_on:
      - notify-start

  - name: test
    image: golang:1.13.1-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test ./...
    depends_on:
      - notify-start

  - name: docker
    image: plugins/docker
    when:
      branch:
        master
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_password
      repo: pztrn/discordrone
      auto_tag: true
    depends_on:
      - test
      - lint
